# -*- coding: utf-8 -*-
"""fe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10-KGGRDrWJRKYlmcXDxN-yiHdWjOkEvt
"""

from options.train_options import TrainOptions
from data import DataLoader
from models.layers.mesh import Mesh
import os

if __name__ == '__main__':
    opt = TrainOptions().parse()
    #dataset=DataLoader()
    oggetti=os.listdir('/content/MeshCNN/checkpoints/ogg/meshes/')
    with open('features.txt', 'w') as file:
        i=3
        for i in range(len(oggetti)):
              mesh= Mesh('/content/MeshCNN/checkpoints/ogg/meshes/'+ oggetti[i], opt)
              edge_features = mesh.extract_features()
              file.write(str(edge_features))
              file.write('\n')
              i=i+4
    file.close()
     
