# -*- coding: utf-8 -*-
"""fe

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10-KGGRDrWJRKYlmcXDxN-yiHdWjOkEvt
"""

from options.train_options import TrainOptions
from data import DataLoader
from models.layers.mesh import Mesh

if __name__ == '__main__':
    opt = TrainOptions().parse()
    #dataset = DataLoader(opt)
    mesh= Mesh('/content/MeshCNN/checkpoints/ogg/meshes/model4_simplified_3.obj', opt, hold_history=False, export_folder=self.opt.export_folder)
    edge_features = mesh.extract_features()